language: node_js
node_js:
  - lts/*
install:
  - npm install
before_script:
  - rm -rf ./server/node_modules
  - rm -rf ./server/package-lock.json
  - npm install --prefix server
before_deploy:
  - gem install mime-types -v 2.6.2
deploy:
  provider: heroku
  api_key:
    secure: BDzlgJ7uGqSa9dDvDrPNYUJRQM8BVcx0H3IJDeNvQuVSy2KjwP46vA21ViBxkV20IGNva4mqCYXCvvTZ0tZowwmR9M0XvdfneaaSZnHHVj6wZ6MkUMzoKDqeaW+0HDhmbHVhTL8rARaUFx/cnotNaCngvptP5GOIzUq2gbeAkd7MteyKkHFzJQTPy2SFGFBNEFDibdCklJS1JDN+Z1ANjxr3BOedrxC3jmcSiy7WzoZMmrhCQfru0mNYX1pWC9RC8RxnIJpfgHMlR30Fe6HPS45EJlq6kyUXt1MswOyu39fmuyJlds41pZG/cHBVw95nSRHT+Ot04qzeD4UcuxNrzlMhOVf140ryuJkuNaHmiqHTGc5rOQL0uf/wzu482PZYvg+h53ZYXYNuJ7GMv0vFWGVkYFjxmx1zra3PyzODgE8JJk9cSsvjfS78zFZwvVozGUDm8G7EZqnzT/MVVyATnvLF+7p2ZR536ca8KQ2bf39AF+5fZSFp0z+NlIioIYeW0b5w70mMPZh/WiNOhuZfCbsORh7sdLVIeamASzWYxaXTHLP49LIdgxoo5mVNaWONgExSqXuPR4Y7N4qI/5PMIEfpsJ257jOddOXNj9AtTlSezmK9M5QRecQiiWITnBv0PJ1FwJgY/XH4SNxfoeETN0YpARFftnzM6NhY7EAxev0=
  app: automeal
  skip_cleanup: true
  on:
    repo: automeal/AutoMeal
