language: node_js
node_js:
  - lts/*
install:
  - npm install
before_script:
  - rm -rf ./server/node_modules
  - rm -rf ./server/package-lock.json
  - npm install --prefix server
before_deploy:
  - gem install mime-types -v 2.6.2
deploy:
  provider: heroku
  api_key:
    secure: URMnPYf9p6rVFW/qp9rj3VEKaVg9AQvhEyQcODOQQhHKxqfUbcWLXYn4wxcU8ci9nzB9yaUNcIkRCBUn4S1ikIE5W2R4NLQCTTEYx14kjYrxptuWk1BBaTII+zHhPryEX5MOQmqtzJFD7vDlczLZjgNmDELI8MtlpYe8RMEOM7vbcJnvVFSknQMIjIq86YLNn7INKfH1jLgKjxX5iLBVGf5mB1+HiWqodd+NUncyY8PZ3wUg7tgspJVIG6YOLrQ/7OOIIdgCWUXRpUSdQwRdluL3BTghUuPCes3ir4WeAjMsvrKLnWKUs95bW2nxhmGJnl10qkxjDVK0skaq15Z7wx6q2Ofy7PDMTPfLq6w97TrTbvx3rVJc3PTcXkcDNaQiwtpY6+6CubDgsTrgTun2Fhn6fZPCKfeNmXwtLEK8V5s5kT+n9Zf7Hzb2qDNurY6BcxOEUuYf0oeA69ijgbVRCC9/+QN9MqCGePsheWDReJT2kcl7d9TwMdGE+D8arVOscYjwEKxxfO+c1+H0j8IInDVsfcFXqZg75eJd9DaXzXzvog64IpjLuKG0fFu+oXjxx7/r0DQfpTDOo18r38waSkB3VTGMp0GyByEYhfUzkfas4pSyP/xEZKxc4eNaDHVxdov9TIUstbrp9bJgshRka95LZsnfUOdfGaukRvGizwU=
  app: automeal
  skip_cleanup: true
  on:
    repo: automeal/AutoMeal
