language: node_js
node_js:
- lts/*
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
before_script:
- npm install --prefix server
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
  provider: heroku
  api_key:
    secure: R52zpzsdiHBZYrD3vzgGrN+5j2Lb6ZrpUU0JpjLh1+d9SRQ3Kw3CX7UnTpISIjlzNW4eR3+7y02GNtyBds6k0BG7hXkoiBVsUuDhUpi7hfptMBsDB0+Hkc35XbKW4al4gKU98ZayBhhvv5qKkVBW9yeWymh2Iz1iBcQn11JhocymNXBAX3a1EQOu+l9CfhL3XjwI+IncIvZhbnQDOtQLm3ekxjWfVGdblUWh6Q1aNchETlDVjJw7Ipehtybrx+8nAwbaZtM2vL66cNZ/SmnH3QWmppfLnjqpxMGZv3pl8rNmqPUJTUcTEwVbJxmYv8oQYrcc0STNwWoLOreqWaIGiC0CRTmq6HHP1wIEnHMNWPleAfyA5cHAAQtXa/GJ6l4v1yXniZdXP0RCGtAN4clALCOIwog3f9CjdSUxW+wbn0WsaInDFsh1QRK5Hh0oguVWQM+CsajRNHqitgHssE/ZCWgNFf9D01FzpS/NFYRdY2k2f9YnXjixbqC5StHNtr8WcdOiGY8v8GugJlWHzHY5VNu69nzA3bLW+b1f13Gnp9+DKrEEa5uwBUlSLsC/4Inkfao1DTvOjOGG0SFdbmmEsLGPMvQm7whWEzywi57psFR4AeA/9xE5ch3sfrWV+PjUZI8ZB/g4lzxcj97tyUPqnOJX4Lmzrswkg00ABHm3ug4=
  app: automeal
  skip_cleanup: true
  on:
    repo: automeal/AutoMeal
