language: node_js
node_js:
- lts/*
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
before_script:
- npm install --prefix server
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
  provider: heroku
  api_key:
    secure: kV1VbPfjqDb3BXGRifsobbDsp4UnskyoLVLD6t6Q7TRDuI+FfS5BfTUd8MbF7MJlDRXmSpElHoJA2f9DYaPlkD9278LS/dxZWOJmCpwy165Knu3A0RXxGzsqGUNknXmBVgGyi61H0IMZjbZPo9Nwbq+Q2Em44Z0RixVzMYJjqqL3uBouvpSG/jwoLpmQPBfd3Pengabyf5e/aZ+ZMFPzWI8aMCr0Y4eR9JyH9i31wvWeeQgXCsC806tEM/F8oxTuTt284eLUQLCXooWwun6DyNKraUST9AZMh63MXrgqUdxiMzE+gDPidaSaiKLXoIEvSrv7Y0yL/udVsNAOjW4Ejnz0gAebIKMXqtP2w7o8xxBlmULSZDzbtvWPKN7eBNMU6M/xh/pNTOYpyXRGAFP57t0SX8zYVsIhX2w1dHSnTIxdjMQrM9EglGXgw2F9d2Xg9I02JuTXUVjNFc4PNglnLbH0fwg3pB/5vxJ495nkshPakcsgF82RhffVJYIls3aJtlqnwngXGZHRr1eTxYHzVperFL9k71xsOhb3gXVP5PNB0tOz6+PvrTAVKjydsGP6cdMK5XNadg5YsR4KVb2T3mJ0O4B+IKvvQonY9/YWTJ21SV6I+liN3ZLSEh4erWgikf2yinp2gFFfdM7JcZP4uzzXRUd9tsdqxRfSPVtxmDo=
  app: automeal
  skip_cleanup: true
  on:
    repo: automeal/AutoMeal
