language: node_js
node_js:
- lts/*
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
before_script:
- npm install --prefix server
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
  provider: heroku
  api_key:
    secure: OxULxu2nC2MahSwOw0y4kn4Hnrc3cobcGUwsvpa2JovxryaztPRCj71+DPUIQlmViIOeNw6rf4wUB0gPGi/s1K6zZ+12lfDYw5rLFr+JhbghT2edMu8n1OjBfpG6OPfJ/HgyMaIkRPRy9vL8S8wQEqF4OBbFXTS8kZxI4fgG01PN7KCy1Z5h26IVADmQgGIbThMLntNvO3y/+Gn7501ltXc5TaL9gaZgFEM2TUvBtb6Paxg9j/aQN34HQUYA1FO8wHjiITOfnnVDtoC5fIR0IruGQFKFjap1B/puUxc0HOPvB2HO29eoXK6NzQtwLMajxv5W/pyT1nhE2GVihK09gSkGwZjpt8ny539elgsjTLgmx5kwXndcak08PF/7WX3EIXp1kHwT9Yf4+plg2nrfrlmQAozcjUeZWz67pqldJOZE7jraTCM448k1Wn1s5pGXpgLYIytkpImN6C1litFCVgf4OlAyS05rmYAQIKFE/wmJlTAioZOjyN9bIczK2M5t5dVoa3mT1WmndTLGILfOS85Kbu7+B4tQHxED0nMPVrYHNxL4751GSxBxFVgZ9XPu6uwu0CwIXrzZoxLogKToNOT2Epm5IiD4qUtrEHePOzmFH15UvySH+S8tMdMgOhlZC5vOrec2vXv7y8ZRziXM5oPR8Y+zUUK7mC2B4TtbA70=
  app: automeal
  skip_cleanup: true
  on:
    repo: automeal/AutoMeal
