language: node_js
node_js:
- lts/*
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
before_script:
- npm install --prefix server
before_deploy:
- gem install mime-types -v 2.6.2
- travis encrypt $(heroku auth:token) --add deploy.api_key --pro
deploy:
  provider: heroku
  api_key:
    secure: mlTIgxWn0oE8TgBMwj2ExcnNndBLFSdLWOYHFtP/6NN2+G60FvvibDxY9m+iGVqslfdgaCqH8XMt6hzCgI0tVYnOZVmxDhIFxi+kDgRvpz8C5IOTLEtllmHhmADDA9cUkPIB+sfwR6FdS68Hlpf1hfGTQzLDFL98RG/J016A43N4vuGAHKAdC4C+rhGZ4hM5AmZpwZNyp5gwaX9VmuFBfuhKqgWixWDIFY99rfKDw0ZRdKJjwqrxj7gwpFFeb7Ngtg4OWJRSZQ8SIyMnrhujVNVWBsHIv8JpVuNU4iNZIhpHp6Jw2j65w6Z1iytrkoWMr63i04hs6LqIZDIxyYwwK/i6AM4phTiBTCI7LUuNnMjJICYZoSE66uYqUpxBOO+zz2RtUQjcnNwWMZYXkY9Ud+IPDJ7vJzWQbu/7ay+FHfqf3y06fsDAwbKIH5v0g2BmvLK9J7z0GGZ+JdIF5g9dWlf8qi/NmvTrm2WNU3DHKJqCq4JSEvuITEYuLeq7HurWis3QFe0Y1wgY6NaL5IHNLMjR9xWvXAC2Y9lJ2FDyghpBwSdxVGcD4YrPtUiGvq6q7QEAEhjrqGxhPo05SuuOcNfL+t3FdMsctiRzleEJbSGGGC9QWypFkDZ5/uv3S35mc5RRlI6rSUom703ug9PITGeAzQ6MV0z58G5A4zBpeIY=
  app: automeal
  skip_cleanup: true
  on:
    repo: automeal/AutoMeal
