language: node_js
node_js:
  - lts/*
install:
  - npm ci
cache:
  directories:
    - '$HOME/.npm'
before_script:
  - npm install --prefix server
before_deploy:
  - gem install mime-types -v 2.6.2
deploy:
  provider: heroku
  api_key:
    secure: dFlNljrg0gxyxntZenW5JIYGat6+wwmuhmDtdqCzFFWbgkn1goQcCiju2rnEY/rsgyZb0XKgW4lDV1w/j8fMJRZbiKxHje2fm2Gu2kwyKdCqTDjTv0pfhjIqFvJu0Oxk88Vj+oSEJNhfUy+93V586FvUr8JX1U8hefZjG9UIAiubOWFr5E0cCBTjrIb0QBaYVVvMCwk1zifsnc7eNIL+jdvsWlVk07hc/6xIx9GwrXTa0JhIl+opGeD56o69w0D7MjuXTvRaKJk53I7LVAaPtLgRlpVpp/B9/DrvfGHoLiUYUxOD3nB+spqqqG9+r5FoACyZkHAZA2+NWbn3EFz70CZkACzCB5UNigIdP9Snfq5tzUEfaf4BSYzBCmNqyfSNSoDIQY1TBF1IswCgzXbbsQ1FZ0g++C/xUojU+w3Wh8VgzoaeFyiVDcALjeLyGy6cX6lWgTTHHOgL3wAMh2kcQMiGMTnplxLj7qMB4gS8PZQI3F1E5tgN1CnFcCgQpLK6ouj5MxVxiMRmIPMUchxYvXbNFP6FD8JA1N79jF73z7T0nRggViwbMDHS8Y9YrlWuejs5paziSUe7fJCizl45V/yRnJXVyKdFm8t8eGClb47z00LMkDbOpGg1X2f+PxUr4iFZFMajHqZQDpbn7qwrl8xEdwL/FSmg3jQmlyk8sJk=
  app: automeal
  skip_cleanup: true
  on:
    repo: automeal/AutoMeal
